# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "MIN SUN"

twitter:
  username:         "__modo_"
#facebook:
#  app_id:           1234
#    publisher:      1234

author:
  name:             KIM MIN SUN
  facebook:
  twitter:          __modo_
  github:           minsunkim2
  linkedin:         
  medium:
  tumblr:
  email:            star1132@nate.com

# Google-analytics
google-analytics:
  id:               "UA-82148706-1"

# Disqus
disqus:
  id:                "aweekj"

# URL
url:                "https://minsunkim11.github.io" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      "/page:num/"

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive/index.html"
  - name:           "Tags"
    url:            "/tags/index.html"
  - name:           "TIL"
    url:            "https://github.com/AWEEKJ/TIL"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
